controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    joint_traject:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController


position_controller:
  ros__parameters:
    joints:
      - world_base_joint
      - base_seg1_joint
      - seg1_seg2_joint
      - seg2_seg3_joint
      - seg3_seg4_joint
      - seg4_seg5_joint
      # - world_base_offset
      # - base_seg1_offset
      # - seg1_seg2_offset
      # - seg2_seg3_offset
      # - seg3_seg4_offset
      # - seg4_seg5_offset



joint_traject:
  ros__parameters:
    joints:
      - world_base_joint
      - base_seg1_joint
      - seg1_seg2_joint
      - seg2_seg3_joint
      - seg3_seg4_joint
      - seg4_seg5_joint
      # - world_base_offset
      # - base_seg1_offset
      # - seg1_seg2_offset
      # - seg2_seg3_offset
      # - seg3_seg4_offset
      # - seg4_seg5_offset

    command_interfaces:
      - position
    state_interfaces:
      - position
      # - effort

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      # joint1:
      #   trajectory: 0.05
      #   goal: 0.03

